made stricter checking of residue types in sequence
kbaseapps/kb_blast pull request #33
Opened 2018-05-09 21:30 UTC by dcchivian

2018-05-09 21:33 UTC, dcchivian commented
psiBLAST App was letting nucleotide-only MSAs through and failing during execution.  Added stricter tests throughout BLAST Apps that require protein input.  Unit tests are passing.

2018-05-09 21:47 UTC, dcchivian commented
@sychan @psdehal @scanon @JamesJeffryes addresses PTV-1077

2018-05-09 21:52 UTC, JamesJeffryes requested changes
The logic looks fine but I think it would be pretty simple and valuable to add unit tests that make sure the right error is raised for these cases where nucleotides are passed to these functions

2018-05-09 21:52 UTC, JamesJeffryes commented on lib/kb_blast/kb_blastImpl.py
> +                self.log(invalid_msgs,"Need protein query sequence.  BAD nucleotide record for sequence_id: "+header_id+"\n"+sequence_str+"\n")
This line is too long, please break into multiple lines

2018-05-09 23:28 UTC, dcchivian commented
@JamesJeffryes I made your suggested changes.  Please review.  Thanks!

2018-05-09 23:29 UTC, dcchivian commented
unit tests (including new one with nucleotide MSA for PSI-BLAST) are all passing

2018-05-10 01:31 UTC, JamesJeffryes approved these changes
I can confirm the tests check out. I'm ok with this PR

2018-05-10 02:10 UTC, merged